fix(pt): fix model_def_script (#3671)
When executing

```sh
cd examples/water/se_e2_a
dp --pt train input.json
dp --pt freeze
dp convert-backend fromzen_model.pth frozen_model.pb
dp convert-backend fromzen_model.pb frozen_model.pth
```

An error throws in the last step:

```
TypeError: deepmd.tf.descriptor.descriptor.Descriptor() got multiple values for keyword argument 'ntypes'
```

The reason is that `model_def_script` is modified and further saved


https://github.com/deepmodeling/deepmd-kit/blob/3b230c2cceea40db3b03a017c063e4c7a78bbb6a/deepmd/pt/model/model/__init__.py#L145